[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
quilt_loom = "1.4.+"

quilt_loader = "0.23.1"
quilted_fabric_api = "8.0.0-alpha.3+0.91.2-1.20.2"

modmenu = "8.0.1"
lazydfu = "0.1.3"

hephaestus = "1.20.1-3.6.3.241"
inventorio = "4619078"

universalgraves = "3.1.1+1.20.2"
sgui = "1.3.0+1.20.2"
placeholder-api = "2.2.0+1.20.2"
polymer = "0.6.0+1.20.2"
predicate-api = "0.3.0+1.20.2"
common-protection-api = "1.0.0"
server-translations-api = "2.0.0+1.20"
fabric-permissions-api = "0.2-SNAPSHOT"

[libraries]
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
quilted_fabric_api_deprecated = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api-deprecated", version.ref = "quilted_fabric_api" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
lazydfu = { module = "maven.modrinth:lazydfu", version.ref = "lazydfu" }

hephaestus = { module = "maven.modrinth:hephaestus", version.ref = "hephaestus" }
inventorio = { module = "curse.maven:inventorio-491073", version.ref = "inventorio" }

universalgraves = { module = "maven.modrinth:universal-graves", version.ref = "universalgraves" }
sgui = { module = "eu.pb4:sgui", version.ref = "sgui" }
placeholder-api = { module = "eu.pb4:placeholder-api", version.ref = "placeholder-api" }
polymer-core = { module = "eu.pb4:polymer-core", version.ref = "polymer" }
polymer-resource-pack = { module = "eu.pb4:polymer-resource-pack", version.ref = "polymer" }
polymer-virtual-entity = { module = "eu.pb4:polymer-virtual-entity", version.ref = "polymer" }
predicate-api = { module = "eu.pb4:predicate-api", version.ref = "predicate-api" }
common-protection-api = { module = "eu.pb4:common-protection-api", version.ref = "common-protection-api" }
server-translations-api = { module = "xyz.nucleoid:server-translations-api", version.ref = "server-translations-api" }
fabric-permissions-api = { module = "me.lucko:fabric-permissions-api", version.ref = "fabric-permissions-api" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
quilted_fabric_api = ["quilted_fabric_api", "quilted_fabric_api_deprecated"]
universalgraves_runtime = ["sgui", "placeholder-api", "polymer-core", "polymer-resource-pack", "polymer-virtual-entity", "predicate-api", "common-protection-api", "server-translations-api", "fabric-permissions-api"]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version.ref = "quilt_loom" }
